### ISSUE TITLE
.since could also subscribe after querying events

### ISSUE THREAD

**Issue by glynnbird** [MattCollins84/couch-pubsub#2]
When doing `pubsub.since`, the library performs a query to find all events >= a specified date. It would be cool if it did this and _then_ set up a subscription for changes. That way the user can use `.since` as a drop-in replacement for `.sub` when the last known event date is known.

**Comment by MattCollins84** [comment]
I did this for the command line version, not sure why I didn't do it for the JS version! I'll have a go..

**Comment by MattCollins84** [comment]
done, this. kind of.
