### ISSUE TITLE
A browser client?

### ISSUE THREAD

**Issue by mikkokam** [MattCollins84/couch-pubsub#3]
Very cool!

I've been using PubNub (pub-sub) + CouchDB (data) as a test platform for distributed and decoupled system prototypes recently.  By using CouchDB for the pub-sub part as well, everything can be run from CouchDB.

**Question: will there be a browser client?**
Just to test, I made a rapid hack to run in browser or a mobile app. PouchDB is smallish (150 kB) and stable, so used it to test an implementation.

http://codepen.io/mikkokam/pen/MwZaXZ

Seems to be viable. It might be possible to create a cross-platform js solution using PouchDB as it runs on browser and Node, too (unlike nano, I suppose).
Or - there might be separate clients for browser, Node and native apps - just like PubNub has. By defining the API and supporting **since** and other features you might have in the future, this could be a really nice distributed pub-sub platform...

**Comment by MattCollins84** [comment]
Very interesting idea, that would be quite cool... I haven't looked at PouchDB yet, I will take a look! I might not get to this for a week or so, if you want to have a go then feel free :)

**Comment by MattCollins84** [comment]
Actually, I might get a chance to have a go tomorrow.

**Comment by mikkokam** [comment]
You can use PouchDB in place of nano; to connect to CouchDB. But it also enables a local database, and even syncing the two.

**Comment by MattCollins84** [comment]
New version released that supports PouchDB and works form the browser - great idea, thanks!

**Comment by mikkokam** [comment]
Excellent work, thanks!
